export default {
  login: "p4avinash",
  id: 46785501,
  node_id: "MDQ6VXNlcjQ2Nzg1NTAx",
  avatar_url: "https://avatars.githubusercontent.com/u/46785501?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/p4avinash",
  html_url: "https://github.com/p4avinash",
  followers_url: "https://api.github.com/users/p4avinash/followers",
  following_url:
    "https://api.github.com/users/p4avinash/following{/other_user}",
  gists_url: "https://api.github.com/users/p4avinash/gists{/gist_id}",
  starred_url: "https://api.github.com/users/p4avinash/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/p4avinash/subscriptions",
  organizations_url: "https://api.github.com/users/p4avinash/orgs",
  repos_url: "https://api.github.com/users/p4avinash/repos",
  events_url: "https://api.github.com/users/p4avinash/events{/privacy}",
  received_events_url: "https://api.github.com/users/p4avinash/received_events",
  type: "User",
  site_admin: false,
  name: "Avinash",
  company: "Ashriya Infotech Pvt. Ltd.",
  blog: "",
  location: "Mohali",
  email: null,
  hireable: null,
  bio: "Learning a little everyday",
  twitter_username: "p4avinash",
  public_repos: 29,
  public_gists: 0,
  followers: 4,
  following: 13,
  created_at: "2019-01-17T13:47:45Z",
  updated_at: "2022-02-02T05:19:02Z",
}
